name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Build
        run: make

      - name: Create tarball
        run: |
          mkdir release
          cp meu-comando release/
          cp README.md release/ || true

          tar -czf meu-comando-linux-x86_64.tar.gz release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            meu-comando-linux-x86_64.tar.gz
